language: objective-c
osx_image: xcode7.3
before_install:
- brew cask uninstall oclint
- brew tap oclint/formulae
- brew install oclint
script:
  - xcodebuild | tee xcodebuild.log
  - oclint-xcodebuild
  - oclint-json-compilation-database
